export interface DetailCiri {
  label: string;
  val: string;
}

export interface DiagnosisItem {
  id: string;
  nama: string;
  ilmiah: string;
  tipe: string;
  badge: string;
  fase: string[];
  keparahan: string;
  gejalaKunci: string[];
  semua_gejala: string[];
  lokasi: string;
  ciri_khas: DetailCiri[];
  pengendalian: string;
  catatan_kalbar?: string;
}

export interface Symptom {
  id: string;
  label: string;
  desc: string;
}

export const DB: {
  hama: DiagnosisItem[];
  penyakit: DiagnosisItem[];
  defisiensi: DiagnosisItem[];
} = {
  hama: [
    {
      id:'penggerek',
      nama:'Penggerek batang padi',
      ilmiah:'Scirpophaga incertulas / S. innotata / Chilo suppressalis',
      tipe:'Hama',
      badge:'badge-danger',
      fase:['semai','vegetatif','bunting','generatif'],
      keparahan:'Tinggi',
      gejalaKunci:['sundep','beluk','bekas_gerek','daun_mengering'],
      semua_gejala:['sundep','beluk','bekas_gerek','daun_mengering','anakan_mati','daun_mengering_atas'],
      lokasi:'Batang, pelepah daun',
      ciri_khas:[
        {label:'Fase vegetatif',val:'Pucuk layu & mengering (sundep) — cabut mudah'},
        {label:'Fase generatif',val:'Malai putih & hampa (beluk)'},
        {label:'Bukti fisik',val:'Bekas gerekan di dalam batang, kotoran/frass'},
        {label:'Telur',val:'Kelompok telur bersisik putih kecoklatan di daun'},
      ],
      pengendalian:'Potong & bakar tunggul. Tanam serempak. Gunakan varietas tahan. Lepas Trichogramma spp. Insektisida: fipronil, karbosulfan sesuai ambang (2 sundep/m² atau 5% beluk).',
      catatan_kalbar:'Spesies dominan di pasang surut: S. innotata (penggerek putih). Dapat ditekan tanpa insektisida dengan manajemen air dan pola tanam serempak.',
    },
    {
      id:'wereng_coklat',
      nama:'Wereng batang coklat (WBC)',
      ilmiah:'Nilaparvata lugens',
      tipe:'Hama',
      badge:'badge-danger',
      fase:['vegetatif','bunting','generatif'],
      keparahan:'Sangat tinggi',
      gejalaKunci:['hopperburn','daun_kuning','tanaman_rebah'],
      semua_gejala:['hopperburn','daun_kuning','tanaman_rebah','anakan_berkurang'],
      lokasi:'Pangkal batang (permukaan air)',
      ciri_khas:[
        {label:'Gejala khas',val:'Hopperburn — daun kuning & kering seperti terbakar, dari bawah ke atas'},
        {label:'Tanda fisik',val:'Nimfa & imago coklat di pangkal batang; terdapat embelan lilin putih'},
        {label:'Bentuk kerusakan',val:'Lingkaran/bercak gosong meluas, tanaman roboh (fuso)'},
        {label:'Vektor',val:'Menularkan virus kerdil rumput & kerdil hampa'},
      ],
      pengendalian:'Tanam varietas tahan (Inpara 3, Inpara 6). Hindari pupuk N berlebihan. Jaga musuh alami (laba-laba, kumbang). Insektisida: BPMC, imidakloprid, tiametoksam — hanya jika >10 ekor/rumpun.',
      catatan_kalbar:'Di lahan pasang surut Kalbar frekuensi insektisida rendah sehingga musuh alami melimpah. Ledakan biasanya terpicu pemupukan N dosis tinggi.',
    },
    {
      id:'tikus',
      nama:'Tikus sawah',
      ilmiah:'Rattus argentiventer',
      tipe:'Hama',
      badge:'badge-danger',
      fase:['vegetatif','bunting','generatif'],
      keparahan:'Tinggi',
      gejalaKunci:['batang_terpotong','kerusakan_tengah','malai_rontok'],
      semua_gejala:['batang_terpotong','kerusakan_tengah','malai_rontok','lubang_tanah'],
      lokasi:'Seluruh petakan, terutama tengah',
      ciri_khas:[
        {label:'Pola kerusakan',val:'Dimulai dari tengah petakan, meluas ke pinggir — khas serangan tikus'},
        {label:'Bukti fisik',val:'Batang terpotong miring, sisa potongan berserakan'},
        {label:'Fase bunting',val:'Malai dipotong sebelum panen, gabah berserakan'},
        {label:'Jejak',val:'Lubang di pematang, jalur (runway) di antara rumpun'},
      ],
      pengendalian:'Gropyokan massal serentak. Pasang perangkap TBS (Trap Barrier System) di awal tanam. Pengelolaan habitat (pangkas vegetasi pematang). Rodentisida hanya di titik serangan berat.',
      catatan_kalbar:'Pematang lebar dan semak di sekitar lahan rawa pasang surut menjadi sarang utama. TBS sangat efektif bila dilakukan kelompok tani bersama.',
    },
    {
      id:'walang_sangit',
      nama:'Walang sangit',
      ilmiah:'Leptocorisa oratorius',
      tipe:'Hama',
      badge:'badge-warning',
      fase:['generatif'],
      keparahan:'Sedang',
      gejalaKunci:['gabah_hampa','beras_berubah_warna','bau_busuk'],
      semua_gejala:['gabah_hampa','beras_berubah_warna','bau_busuk'],
      lokasi:'Malai (fase pengisian bulir)',
      ciri_khas:[
        {label:'Gejala',val:'Gabah hampa, beras mengapur/berubah warna, malai berbintik hitam'},
        {label:'Tanda fisik',val:'Imago coklat berbau menyengat, nimfa hijau di malai'},
        {label:'Telur',val:'Telur coklat pipih berbaris 12–16 butir di permukaan daun'},
        {label:'Waktu',val:'Aktif pagi & sore hari, terutama saat pengisian bulir'},
      ],
      pengendalian:'Tanam serempak untuk memutus siklus. Perangkap bangkai keong/kepiting di sawah. Musuh alami: Telenomus spp. (parasitoid telur). Insektisida bila >5 ekor/rumpun.',
      catatan_kalbar:'Populasi meledak bila panen tidak serempak. Penggunaan bangkai keong mas sebagai perangkap terbukti efektif di lahan rawa.',
    },
    {
      id:'keong_mas',
      nama:'Keong mas',
      ilmiah:'Pomacea canaliculata',
      tipe:'Hama',
      badge:'badge-warning',
      fase:['semai','vegetatif'],
      keparahan:'Tinggi (lahan baru)',
      gejalaKunci:['tanaman_habis_dimakan','bibit_hilang','telur_pink'],
      semua_gejala:['tanaman_habis_dimakan','bibit_hilang','telur_pink'],
      lokasi:'Bibit muda (0–21 HST), batang bawah permukaan air',
      ciri_khas:[
        {label:'Gejala',val:'Bibit/tanaman muda hilang atau batang terpotong di bawah permukaan air'},
        {label:'Tanda fisik',val:'Kelompok telur berwarna merah muda/oranye mencolok di batang & pematang'},
        {label:'Waktu',val:'Paling merusak 7–21 HST (bibit muda). Populasi tinggi di lahan baru/tergenang'},
      ],
      pengendalian:'Buru & hancurkan telur secara manual. Pasang saringan di pintu air. Penundaan genangan hingga bibit berumur >3 minggu. Itik/bebek di lahan. Moluskisida bila populasi >4 ekor/m².',
      catatan_kalbar:'Sangat umum di lahan rawa pasang surut Kalbar, terutama di lahan bukaan baru. Keong mas invasif dan sangat merugikan pada tanam pindah.',
    },
    {
      id:'ganjur',
      nama:'Hama ganjur',
      ilmiah:'Orseolia oryzae',
      tipe:'Hama',
      badge:'badge-warning',
      fase:['semai','vegetatif'],
      keparahan:'Sedang',
      gejalaKunci:['tabung_ganjur','daun_menggulung_semai'],
      semua_gejala:['tabung_ganjur','daun_menggulung_semai'],
      lokasi:'Titik tumbuh anakan',
      ciri_khas:[
        {label:'Gejala khas',val:'Anakan berubah menjadi tabung hijau-putih mirip "pelepah bambu" (tabung ganjur)'},
        {label:'Mekanisme',val:'Larva menghisap titik tumbuh → anakan tidak berkembang & membentuk tabung'},
        {label:'Populasi',val:'Meningkat pada curah hujan tinggi dan lahan selalu tergenang'},
      ],
      pengendalian:'Tanam varietas tahan (Inpara 3, 6, 7). Pengaturan air: keringkan lahan sesaat setelah tanam. Musuh alami: Platygaster oryzae. Insektisida karbofuran bila >5% tabung ganjur.',
      catatan_kalbar:'Endemik di beberapa wilayah pasang surut Kubu Raya dan Pontianak. Sering muncul di awal musim hujan.',
    },
    {
      id:'orong_orong',
      nama:'Orong-orong (anjing tanah)',
      ilmiah:'Gryllotalpa orientalis',
      tipe:'Hama',
      badge:'badge-warning',
      fase:['semai','vegetatif'],
      keparahan:'Sedang',
      gejalaKunci:['tanaman_layu_akar','terowongan_tanah'],
      semua_gejala:['tanaman_layu_akar','terowongan_tanah','anakan_sangat_sedikit'],
      lokasi:'Akar dan batang bawah tanah',
      ciri_khas:[
        {label:'Gejala khas',val:'Tanaman layu dan mati mendadak secara sporadis — akar terputus/terpotong saat dicabut'},
        {label:'Bukti fisik',val:'Terowongan kecil di permukaan tanah; serangga hitam-coklat bersayap, kaki depan seperti cangkul'},
        {label:'Pola kerusakan',val:'Acak/sporadis, tidak membentuk pola dari tengah (beda dengan tikus)'},
        {label:'Waktu aktif',val:'Aktif malam hari; lebih parah di lahan macak-macak atau kering sesaat'},
      ],
      pengendalian:'Genangan air menekan populasi — orong-orong tidak tahan tergenang terus-menerus. Tangkap dengan lampu perangkap malam hari. Karbofuran granul di tanah bila serangan berat (>2 lubang/m²).',
      catatan_kalbar:'Lebih sering muncul di lahan pasang surut yang berselang-seling kering-macak. Serangan meningkat saat musim kemarau atau lahan sawah bukaan baru yang belum tergenang.',
    },
  ],
  penyakit: [
    {
      id:'blast',
      nama:'Blas / Blast padi',
      ilmiah:'Pyricularia grisea (Magnaporthe oryzae)',
      tipe:'Penyakit (Jamur)',
      badge:'badge-danger',
      fase:['semai','vegetatif','bunting','generatif'],
      keparahan:'Sangat tinggi',
      gejalaKunci:['bercak_belah_ketupat','pusat_abu','blas_leher'],
      semua_gejala:['bercak_belah_ketupat','pusat_abu','blas_leher','daun_terbakar','daun_mengering_atas'],
      lokasi:'Daun, leher malai, buku batang',
      ciri_khas:[
        {label:'Blast daun',val:'Bercak belah ketupat, tepi coklat, pusat abu-abu/putih. Stadium vegetatif.'},
        {label:'Blast leher',val:'Bercak coklat kehitaman di pangkal leher malai — malai patah, hampa'},
        {label:'Kondisi',val:'Berkembang cepat di musim hujan, suhu 24–28°C, kelembaban >90%'},
        {label:'Risiko Kalbar',val:'Penyakit utama padi pasang surut dan gogo di Kalimantan Barat'},
      ],
      pengendalian:'Gunakan varietas tahan: Inpara 1, 2, 3, 6, 7. Hindari pupuk N berlebihan (pemupukan ke-3 ditunda — ganti KCl 5 kg/ha). Fungisida: trisiklazol, karbendazim, difenokonazol bila bercak >5%.',
      catatan_kalbar:'Menjadi momok utama petani Kalbar beberapa tahun terakhir. Inpara 3 dan Siak Raya terbukti paling tahan di lahan pasang surut bergambut Kubu Raya.',
    },
    {
      id:'hdb',
      nama:'Hawar daun bakteri (HDB/Kresek)',
      ilmiah:'Xanthomonas oryzae pv. oryzae',
      tipe:'Penyakit (Bakteri)',
      badge:'badge-danger',
      fase:['semai','vegetatif','bunting','generatif'],
      keparahan:'Tinggi',
      gejalaKunci:['kresek','hawar_tepi','daun_keabu'],
      semua_gejala:['kresek','hawar_tepi','daun_keabu','daun_mengering','daun_menggulung_semai','daun_mengering_atas'],
      lokasi:'Daun (tepi ke tengah)',
      ciri_khas:[
        {label:'Gejala kresek',val:'Tanaman <30 HST: daun menggulung, layu, hijau keabu-abuan, lalu mati'},
        {label:'Gejala hawar',val:'Tanaman dewasa: bercak abu-abu di tepi daun, meluas ke tulang daun, daun mengering'},
        {label:'Uji peras',val:'Potong daun terinfeksi, masukkan air — muncul eksudat putih seperti susu (ooze)'},
        {label:'Kondisi',val:'Berkembang pesat saat hujan deras, luka akibat angin/padi bergesekan'},
      ],
      pengendalian:'Varietas tahan: Code, Angke. Pemupukan N berimbang — hindari dosis tinggi. Jaga drainase, hindari genangan terus-menerus. Tidak ada fungisida yang efektif — pengendalian preventif utama.',
      catatan_kalbar:'Sering meledak setelah hujan deras atau banjir di lahan pasang surut. Sanitasi sisa tanaman penting untuk memutus siklus inokulum.',
    },
    {
      id:'bercak_coklat',
      nama:'Bercak coklat',
      ilmiah:'Bipolaris oryzae (Cochliobolus miyabeanus)',
      tipe:'Penyakit (Jamur)',
      badge:'badge-warning',
      fase:['semai','vegetatif','bunting','generatif'],
      keparahan:'Sedang–tinggi',
      gejalaKunci:['bercak_oval_coklat','bercak_benih','daun_menguning_bercak'],
      semua_gejala:['bercak_oval_coklat','bercak_benih','daun_menguning_bercak','defisiensi_hara'],
      lokasi:'Daun, sekam biji',
      ciri_khas:[
        {label:'Gejala',val:'Bercak coklat gelap–kehitaman, oval/bulat, pada daun. Berbeda dengan blast (tidak belah ketupat)'},
        {label:'Kondisi pemicu',val:'Defisiensi hara (N, K, Si), pH rendah, kekeringan — umum di pasang surut'},
        {label:'Benih',val:'Patogen bertahan di benih — benih terinfeksi jadi sumber inokulum'},
        {label:'Perbedaan blast',val:'Bercak oval tanpa pusat abu-abu. Tidak membentuk pola belah ketupat.'},
      ],
      pengendalian:'Gunakan benih sehat bersertifikat. Perbaiki kesuburan tanah (pupuk N, K, Si). Perbaiki drainase. Fungisida: mankozeb, karbendazim bila intensitas >25%.',
      catatan_kalbar:'Lebih parah di lahan bukaan baru dengan pH rendah and defisiensi hara — sangat khas pasang surut sulfat masam Kalbar.',
    },
    {
      id:'tungro',
      nama:'Tungro',
      ilmiah:'Rice Tungro Virus (RTSV + RTBV) — vektor: Nephotettix virescens',
      tipe:'Penyakit (Virus)',
      badge:'badge-danger',
      fase:['semai','vegetatif'],
      keparahan:'Tinggi',
      gejalaKunci:['daun_kuning_oranye','kerdil_tungro','anakan_sedikit'],
      semua_gejala:['daun_kuning_oranye','kerdil_tungro','anakan_sedikit'],
      lokasi:'Seluruh tanaman (sistemik)',
      ciri_khas:[
        {label:'Gejala khas',val:'Daun menguning–oranye mulai dari daun muda, tanaman kerdil, anakan sangat sedikit'},
        {label:'Vektor',val:'Wereng hijau (Nephotettix virescens) — 1 ekor cukup menularkan'},
        {label:'Perbedaan',val:'Daun kuning-oranye rata (bukan bercak), berbeda dengan kresek atau defisiensi N'},
      ],
      pengendalian:'Tanam varietas tahan/toleran tungro: Inpari 7, Tukad Unda. Kendalikan wereng hijau sebagai vektor. Cabut & musnahkan tanaman terinfeksi. Tidak ada pestisida untuk virus.',
      catatan_kalbar:'Sporadis di Kalbar, berkorelasi dengan ledakan wereng hijau. Tidak setinggi ancaman blast.',
    },
    {
      id:'busuk_pelepah',
      nama:'Busuk pelepah (Sheath blight)',
      ilmiah:'Rhizoctonia solani',
      tipe:'Penyakit (Jamur)',
      badge:'badge-warning',
      fase:['vegetatif','bunting','generatif'],
      keparahan:'Sedang',
      gejalaKunci:['bercak_upih','bercak_tak_beraturan','busuk_pangkal'],
      semua_gejala:['bercak_upih','bercak_tak_beraturan','busuk_pangkal'],
      lokasi:'Upih daun (sheath), dekat permukaan air',
      ciri_khas:[
        {label:'Gejala',val:'Bercak nekrotik tak beraturan di upih daun dekat permukaan air, warna hijau-abu-coklat'},
        {label:'Stadium lanjut',val:'Bercak meluas naik ke daun, tanaman rebah. Sklerotia coklat menempel di batang.'},
        {label:'Pemicu',val:'Populasi rapat, pupuk N tinggi, kelembaban tinggi — khas pasang surut tergenang'},
      ],
      pengendalian:'Kurangi kepadatan tanaman. Pemupukan N berimbang. Jaga drainase. Fungisida: validamisin, tioflonaid bila >30% populasi terserang.',
      catatan_kalbar:'Berkembang di lahan pasang surut yang selalu tergenang dan populasi rapat.',
    },
  ],
  defisiensi: [
    {
      id:'def_n',
      nama:'Defisiensi nitrogen (N)',
      ilmiah:'Kekurangan unsur hara N',
      tipe:'Defisiensi Hara',
      badge:'badge-info',
      fase:['semai','vegetatif','bunting','generatif'],
      keparahan:'Sedang',
      gejalaKunci:['daun_kuning_merata','kerdil_defisiensi','anakan_sedikit'],
      semua_gejala:['daun_kuning_merata','kerdil_defisiensi','anakan_sedikit'],
      lokasi:'Daun tua (bawah) terlebih dahulu → semua daun',
      ciri_khas:[
        {label:'Gejala khas',val:'Daun tua kuning merata mulai dari ujung, tanaman kerdil, sempit, anakan sedikit'},
        {label:'Pola',val:'Menguning dimulai dari daun tua (mobilitas N tinggi) — berbeda dari defisiensi Fe/Zn'},
        {label:'Uji cepat',val:'Gunakan Bagan Warna Daun (BWD/LCC) — nilai <3 = defisiensi N'},
        {label:'Penyebab',val:'pH asam, drainase buruk, tanah bergambut rendah N tersedia — umum di pasang surut'},
      ],
      pengendalian:'Pupuk urea sesuai rekomendasi, dipandu BWD. Pemupukan split (3 kali). Ameliorasi dengan kapur dolomit untuk meningkatkan ketersediaan N.',
      catatan_kalbar:'Di lahan pasang surut gambut Kalbar, N tersedia rendah dan pencucian tinggi. Pemupukan berdasarkan BWD sangat dianjurkan.',
    },
    {
      id:'def_fe',
      nama:'Keracunan besi (Fe toksisitas)',
      ilmiah:'Toksisitas Fe²⁺ — kelebihan ion besi',
      tipe:'Keracunan Hara',
      badge:'badge-danger',
      fase:['semai','vegetatif'],
      keparahan:'Tinggi (dapat turun 30–100%)',
      gejalaKunci:['bercak_coklat_ujung','daun_coklat_ungu','akar_coklat_busuk'],
      semua_gejala:['bercak_coklat_ujung','daun_coklat_ungu','akar_coklat_busuk','kerdil_defisiensi'],
      lokasi:'Daun bawah → seluruh tanaman; akar',
      ciri_khas:[
        {label:'Gejala khas',val:'Bercak coklat kecil di ujung/bawah daun, menyebar ke pangkal. Daun bisa menjadi coklat-ungu.'},
        {label:'Akar',val:'Akar coklat, kasar, jarang, rusak — berbau sulfida. Pertumbuhan sangat terhambat.'},
        {label:'Waktu muncul',val:'1–8 minggu setelah tanam, pada lahan tergenang/reduksi tinggi'},
        {label:'Pemicu',val:'pH rendah, drainase jelek, lahan baru bukaan, defisiensi K/P/Zn bersamaan'},
      ],
      pengendalian:'Perbaiki drainase (saluran tersier). Pengaturan air: genangi 1 minggu – kering 2 minggu. Ameliorasi kapur 1–2 t/ha. Pupuk KCl (memperkuat toleransi). Varietas toleran: Inpara 3.',
      catatan_kalbar:'Masalah UTAMA di lahan pasang surut bukaan baru Kalbar. Kadar Fe²⁺ sangat tinggi pada tanah sulfat masam bergambut dengan drainase jelek.',
    },
    {
      id:'def_k',
      nama:'Defisiensi kalium (K)',
      ilmiah:'Kekurangan unsur hara K',
      tipe:'Defisiensi Hara',
      badge:'badge-info',
      fase:['vegetatif','bunting','generatif'],
      keparahan:'Sedang',
      gejalaKunci:['tepi_daun_coklat','nekrosis_tepi','daun_tua_rusak'],
      semua_gejala:['tepi_daun_coklat','nekrosis_tepi','daun_tua_rusak','daun_mengering_atas'],
      lokasi:'Tepi daun tua → mati',
      ciri_khas:[
        {label:'Gejala khas',val:'Tepi dan ujung daun tua nekrosis (coklat seperti terbakar), mulai dari daun bawah'},
        {label:'Perbedaan',val:'Mirip blast tapi tidak ada bercak belah ketupat. Mirip wereng tapi tidak ada serangga.'},
        {label:'Komplikasi',val:'Defisiensi K memperparah keracunan Fe dan meningkatkan kerentanan blast'},
        {label:'Penyebab',val:'Tanah pasang surut miskin K, pencucian tinggi, pH asam'},
      ],
      pengendalian:'Pupuk KCl 60–80 kg/ha. Pemupukan split bersamaan dengan pupuk N. Ameliorasi tanah untuk meningkatkan KTK.',
      catatan_kalbar:'Defisiensi K sering bersamaan dengan keracunan Fe di pasang surut Kalbar — keduanya saling memperburuk.',
    },
    {
      id:'def_p',
      nama:'Defisiensi fosfor (P)',
      ilmiah:'Kekurangan unsur hara P',
      tipe:'Defisiensi Hara',
      badge:'badge-info',
      fase:['semai','vegetatif'],
      keparahan:'Sedang',
      gejalaKunci:['daun_ungu_merah','anakan_sangat_sedikit','pertumbuhan_lambat'],
      semua_gejala:['daun_ungu_merah','anakan_sangat_sedikit','pertumbuhan_lambat'],
      lokasi:'Daun tua (bawah) dan batang',
      ciri_khas:[
        {label:'Gejala khas',val:'Daun tua berwarna merah-keunguan (antosianin), batang dan tulang daun ungu'},
        {label:'Pertumbuhan',val:'Kerdil parah, anakan sangat sedikit, perkembangan akar terhambat'},
        {label:'Penyebab',val:'Fiksasi P oleh Al & Fe tinggi di tanah asam sulfat — khas pasang surut'},
        {label:'Catatan',val:'Kelebihan P (rare): hambat serapan Zn, Fe, Cu — tidak terlihat secara visual'},
      ],
      pengendalian:'Pupuk SP-36 atau TSP 60–100 kg/ha saat tanam. Ameliorasi kapur untuk mengurangi fiksasi Al/Fe. Bahan organik meningkatkan ketersediaan P.',
      catatan_kalbar:'Fiksasi P oleh Al and Fe sangat tinggi di tanah sulfat masam Kalbar. Pemberian kapur + SP-36 secara bersamaan sangat dianjurkan.',
    },
    {
      id:'def_zn',
      nama:'Defisiensi seng (Zn)',
      ilmiah:'Kekurangan unsur hara Zn (zinc)',
      tipe:'Defisiensi Hara',
      badge:'badge-info',
      fase:['semai','vegetatif'],
      keparahan:'Sedang',
      gejalaKunci:['daun_muda_belang','strip_kuning_daun','kerdil_defisiensi'],
      semua_gejala:['daun_muda_belang','strip_kuning_daun','kerdil_defisiensi'],
      lokasi:'Daun muda (tengah/baru)',
      ciri_khas:[
        {label:'Gejala khas',val:'Daun muda bercak/strip kuning-oranye atau kecoklatan di bagian tengah (belang/strip)'},
        {label:'Waktu',val:'Muncul 2–4 minggu setelah tanam, lebih parah di lahan tergenang'},
        {label:'Perbedaan',val:'Menyerang daun MUDA (berbeda dengan defisiensi N yang mulai dari daun tua)'},
        {label:'Penyebab',val:'pH tinggi atau rendah, genangan lama, defisiensi BO tanah'},
      ],
      pengendalian:'Semprot ZnSO₄ 0.5% (5 g/L air) pada daun. Aplikasi ZnSO₄ ke tanah 10–20 kg/ha. Pengaturan air untuk mengurangi genangan terus-menerus.',
      catatan_kalbar:'Umum di lahan pasang surut yang lama tergenang. Sering berbarengan dengan keracunan Fe.',
    },
  ],
};

export const GEJALA_DB: Record<string, Symptom[]> = {
  semai: [
    {id:'bibit_hilang',label:'Bibit hilang/terpotong',desc:'Bibit dicabut atau batang terpotong di bawah air'},
    {id:'telur_pink',label:'Telur merah muda di batang',desc:'Kelompok telur oranye-pink di batang/pematang'},
    {id:'daun_menggulung_semai',label:'Daun menggulung & layu',desc:'Daun menggulung lalu layu & mati pada bibit muda'},
    {id:'tabung_ganjur',label:'Anakan berbentuk tabung',desc:'Anakan berubah jadi tabung hijau-putih seperti bambu'},
    {id:'daun_kuning_merata',label:'Daun kuning merata',desc:'Semua daun kuning dari ujung, tanaman kerdil'},
    {id:'daun_ungu_merah',label:'Daun/batang ungu-merah',desc:'Warna ungu/merah pada daun bawah dan batang'},
    {id:'daun_muda_belang',label:'Daun muda belang kuning',desc:'Strip/bercak kuning di daun muda (tengah daun)'},
    {id:'bercak_coklat_ujung',label:'Bercak coklat di ujung daun',desc:'Titik coklat kecil di ujung/bawah daun, menyebar'},
    {id:'kresek',label:'Layu mendadak (kresek)',desc:'Tanaman muda layu, hijau keabu, lalu mati'},
  ],
  vegetatif: [
    {id:'sundep',label:'Pucuk layu & mati (sundep)',desc:'Pucuk tengah layu, kering, mudah dicabut'},
    {id:'hopperburn',label:'Tanaman terbakar (hopperburn)',desc:'Daun kuning-kering seperti terbakar, dari bawah'},
    {id:'batang_terpotong',label:'Batang terpotong miring',desc:'Batang terpotong serong, sisa berserakan'},
    {id:'kerusakan_tengah',label:'Kerusakan dari tengah petakan',desc:'Bercak kosong di tengah, meluas ke pinggir'},
    {id:'bercak_belah_ketupat',label:'Bercak belah ketupat di daun',desc:'Bercak coklat berbentuk belah ketupat, pusat abu-abu'},
    {id:'bercak_oval_coklat',label:'Bercak oval coklat di daun',desc:'Bercak bulat-oval coklat gelap, tanpa pusat abu-abu'},
    {id:'hawar_tepi',label:'Hawar dari tepi daun',desc:'Tepi daun abu-abu, meluas ke dalam, daun mengering'},
    {id:'bercak_upih',label:'Bercak di upih/pelepah daun',desc:'Bercak tak beraturan di pelepah daun dekat air'},
    {id:'daun_kuning_merata',label:'Daun kuning merata',desc:'Daun tua kuning merata, anakan sedikit'},
    {id:'daun_kuning_oranye',label:'Daun kuning-oranye menyeluruh',desc:'Daun muda kuning oranye, tanaman kerdil parah'},
    {id:'daun_ungu_merah',label:'Daun/batang ungu-merah',desc:'Warna ungu di daun bawah dan batang'},
    {id:'bercak_coklat_ujung',label:'Bercak coklat di ujung daun',desc:'Titik coklat dari ujung daun menyebar ke bawah'},
    {id:'daun_muda_belang',label:'Daun muda belang kuning',desc:'Bercak/strip kuning di daun muda, daun tengah'},
    {id:'tepi_daun_coklat',label:'Tepi daun tua coklat (nekrosis)',desc:'Pinggir daun tua coklat seperti terbakar'},
    {id:'akar_coklat_busuk',label:'Akar coklat/busuk berbau',desc:'Akar coklat gelap, berbau sulfur/busuk'},
    {id:'anakan_sangat_sedikit',label:'Anakan sangat sedikit',desc:'Jumlah anakan jauh di bawah normal'},
    {id:'tabung_ganjur',label:'Anakan berbentuk tabung',desc:'Anakan berubah jadi tabung hijau-putih'},
    {id:'tanaman_layu_akar',label:'Tanaman layu/mati, akar rusak',desc:'Rumpun layu mendadak lalu mati; akar terputus saat dicabut'},
    {id:'terowongan_tanah',label:'Lubang/terowongan di tanah',desc:'Lubang kecil dan terowongan di permukaan tanah dekat rumpun yang mati'},
  ],
  bunting: [
    {id:'sundep',label:'Pucuk layu (masih mungkin)',desc:'Sundep akhir pada tanaman muda yang bunting'},
    {id:'blas_leher',label:'Leher malai coklat/patah',desc:'Pangkal leher malai coklat kehitaman, malai patah'},
    {id:'hawar_tepi',label:'Hawar dari tepi daun',desc:'Gejala HDB berlanjut ke fase bunting'},
    {id:'bercak_belah_ketupat',label:'Bercak belah ketupat di daun',desc:'Blast daun masih aktif di fase bunting'},
    {id:'bercak_upih',label:'Bercak naik ke daun dari upih',desc:'Sheath blight meluas ke daun'},
    {id:'batang_terpotong',label:'Batang/malai dipotong tikus',desc:'Tikus memotong sebelum panen'},
    {id:'tepi_daun_coklat',label:'Tepi daun tua coklat',desc:'Defisiensi K berlanjut ke bunting'},
    {id:'daun_tua_rusak',label:'Daun tua rusak meluas',desc:'Kerusakan progresif dari daun bawah'},
  ],
  generatif: [
    {id:'beluk',label:'Malai putih hampa (beluk)',desc:'Malai baru keluar putih seluruhnya, gabah hampa'},
    {id:'blas_leher',label:'Leher malai coklat patah',desc:'Blast leher — malai hitam/coklat & patah'},
    {id:'gabah_hampa',label:'Gabah hampa/berubah warna',desc:'Banyak gabah hampa, beras mengapur'},
    {id:'malai_rontok',label:'Malai dipotong/rontok',desc:'Malai dipotong atau bulir berserakan'},
    {id:'bau_busuk',label:'Bau menyengat di sawah',desc:'Aroma busuk dari walang sangit'},
    {id:'hawar_tepi',label:'Hawar daun berlanjut',desc:'HDB masih aktif di fase panen'},
    {id:'daun_mengering_atas',label:'Daun atas mengering',desc:'Daun bendera/atas mengering — bukan gejala normal'},
  ],
};
